// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app/admins": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-管理员"
                ],
                "summary": "管理员列表(分页)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名模糊筛选",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态筛选:1启用/0禁用",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/yhdm_service_internal_service.AdminListResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/authorities": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-权限资源"
                ],
                "summary": "权限资源(菜单节点)列表(分页)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 15,
                        "description": "每页",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "名称模糊",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "标识模糊",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "上级ID",
                        "name": "parent_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "是否菜单:1是/0否",
                        "name": "is_menu",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/yhdm_service_internal_service.AuthorityListResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/authority-detail": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-权限资源"
                ],
                "summary": "权限资源详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "权限资源ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/yhdm_service_internal_service.AuthorityListItem"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/create-admin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-管理员"
                ],
                "summary": "新增管理员",
                "parameters": [
                    {
                        "description": "管理员信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.createAdminReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {id, message}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/create-role": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-角色"
                ],
                "summary": "新增角色",
                "parameters": [
                    {
                        "description": "角色名",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.createRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {id, message}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/delete-admin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-管理员"
                ],
                "summary": "删除管理员",
                "parameters": [
                    {
                        "description": "管理员ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.deleteAdminReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {success, message}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/delete-authority": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-权限资源"
                ],
                "summary": "删除权限资源",
                "parameters": [
                    {
                        "description": "权限资源ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.deleteAuthorityReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {success, message}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/delete-role": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-角色"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "description": "角色ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.deleteRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {success, message}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/get-info": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前登录管理员信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/yhdm_service_internal_service.UserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/login": {
            "post": {
                "description": "用户名+密码(+谷歌验证码)登录，成功返回 JWT。dev 模式跳过 2FA。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "后台管理员登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {token, socket}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/menus": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前管理员可见的菜单树",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/yhdm_service_internal_service.MenuItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/options-admin-role": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-管理员"
                ],
                "summary": "角色下拉选项",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/yhdm_service_internal_service.RoleOption"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-角色"
                ],
                "summary": "权限树(用于给角色分配权限)",
                "responses": {
                    "200": {
                        "description": "data: {list:[PermissionNode]}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-角色"
                ],
                "summary": "角色列表",
                "responses": {
                    "200": {
                        "description": "data: {list:[RoleListItem]}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/save-authority": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-权限资源"
                ],
                "summary": "新增/更新权限资源(id\u003e0 为更新)",
                "parameters": [
                    {
                        "description": "权限资源信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.saveAuthorityReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {id, message}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/save-permission": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-角色"
                ],
                "summary": "保存角色权限",
                "parameters": [
                    {
                        "description": "角色ID与权限列表(逗号分隔)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.savePermissionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {success, message}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/update-admin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-管理员"
                ],
                "summary": "更新管理员",
                "parameters": [
                    {
                        "description": "管理员信息(password 为空则不改密码)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.updateAdminReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {success, message}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/update-role": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理-角色"
                ],
                "summary": "更新角色名",
                "parameters": [
                    {
                        "description": "角色ID与名称",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_admin.updateRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {success, message}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/codes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "超级管理员返回 [\"*\"]",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前管理员的权限码(按钮级)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/yhdm_service_internal_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/yhdm_service_internal_response.Body"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handler_admin.LoginReq": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Vben 登录组件里的验证码字段名可能是 code，这里一并接住。",
                    "type": "string"
                },
                "google_code": {
                    "type": "string",
                    "example": "123456"
                },
                "password": {
                    "type": "string",
                    "example": "admin123"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "internal_handler_admin.createAdminReq": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handler_admin.createRoleReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_handler_admin.deleteAdminReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "internal_handler_admin.deleteAuthorityReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "internal_handler_admin.deleteRoleReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "internal_handler_admin.saveAuthorityReq": {
            "type": "object",
            "properties": {
                "class_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_menu": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "integer"
                },
                "sort": {
                    "type": "integer"
                }
            }
        },
        "internal_handler_admin.savePermissionReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "permission_list": {
                    "type": "string"
                },
                "site_id": {
                    "type": "integer"
                }
            }
        },
        "internal_handler_admin.updateAdminReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handler_admin.updateRoleReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "yhdm_service_internal_response.Body": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "yhdm_service_internal_service.AdminListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "← created_at 格式化",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_login_ip": {
                    "description": "← login_ip",
                    "type": "string"
                },
                "last_login_time": {
                    "description": "← login_at 格式化",
                    "type": "string"
                },
                "nickname": {
                    "description": "← real_name",
                    "type": "string"
                },
                "role": {
                    "description": "← 角色名（role_id=0 为超级管理员）",
                    "type": "string"
                },
                "status": {
                    "description": "← is_disabled 取反：1 启用 / 0 禁用",
                    "type": "integer"
                },
                "switch_google2fa": {
                    "description": "← 有 google_code 为 1",
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "yhdm_service_internal_service.AdminListResult": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/yhdm_service_internal_service.AdminListItem"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "yhdm_service_internal_service.AuthorityListItem": {
            "type": "object",
            "properties": {
                "class_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_menu": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "integer"
                },
                "sort": {
                    "type": "integer"
                }
            }
        },
        "yhdm_service_internal_service.AuthorityListResult": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/yhdm_service_internal_service.AuthorityListItem"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "yhdm_service_internal_service.MenuItem": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/yhdm_service_internal_service.MenuItem"
                    }
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "type": {
                    "description": "前端只渲染 type==1 的节点",
                    "type": "integer"
                }
            }
        },
        "yhdm_service_internal_service.RoleOption": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "yhdm_service_internal_service.UserInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "realName": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/backend",
	Schemes:          []string{},
	Title:            "yhdm_service API",
	Description:      "樱花动漫后台服务 API（由 PHP/Phalcon 迁移至 Go/Gin）。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
